### ISSUE TITLE
Sales Copilot for Outlook add-in v. 10 not available

### ISSUE THREAD

**Issue by Niels-SL** [MicrosoftDocs/microsoft-salescopilot-docs#10]
Is version 10.0.0.11 or newer of the Sales Copilot for Outlook add-in available on all regions? 

Our users see the 'Copy content button' instead of the 'Add to email button' in the suggested email content feature - but we cannot see any available updates in the Microsoft 365 admin center [referenced in the documentation](https://learn.microsoft.com/en-us/microsoft-sales-copilot/install-viva-sales-as-an-integrated-app#update-the-sales-copilot-add-in).
 
![image](https://github.com/MicrosoftDocs/microsoft-salescopilot-docs/assets/46558783/464f1dff-e863-44b6-8a21-2d6be8ef4467)

If version 10 of the Sales Copilot for Outlook add-in is not rolled out in all regions, is there an overview of that somewhere?

Kind regards,
Niels

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e673988-d511-5d36-f6bc-9c2fd3394124
* Version Independent ID: 2e673988-d511-5d36-f6bc-9c2fd3394124
* Content: [Turn on Copilot AI features](https://learn.microsoft.com/en-us/microsoft-sales-copilot/suggested-replies#why-do-sellers-see-the-copy-content-button-instead-of-the-add-to-email-button-in-the-suggested-email-content-feature)
* Content Source: [articles/suggested-replies.md](https://github.com/MicrosoftDocs/microsoft-salescopilot-docs/blob/main/articles/suggested-replies.md)
* Service: **microsoft-sales-copilot**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for your feedback. For product-related feedback, visit https://feedbackportal.microsoft.com/feedback/forum/7fcacc26-460c-ed11-b83d-000d3a4d91d1. Closing this issue.
