### ISSUE TITLE
delete account

### ISSUE THREAD

**Issue by doganyilmaz** [MicrosoftDocs/microsoft-salescopilot-docs#15]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4a7b239-a3e1-2c1a-3655-12842e666e6c
* Version Independent ID: f4a7b239-a3e1-2c1a-3655-12842e666e6c
* Content: [Delete your personal data from Sales Copilot](https://learn.microsoft.com/en-us/microsoft-sales-copilot/delete-personal-data)
* Content Source: [articles/delete-personal-data.md](https://github.com/MicrosoftDocs/microsoft-salescopilot-docs/blob/main/articles/delete-personal-data.md)
* Service: **microsoft-sales-copilot**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Hi @doganyilmaz - could you please elaborate your query?

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
