### ISSUE TITLE
Copilot For, or Copilot In?

### ISSUE THREAD

**Issue by gkcoast2coast** [MicrosoftDocs/microsoft-salescopilot-docs#19]
Is the name of the product/SKU, Copilot for Sales or Copilot in Sales?

For Dynamics 365 Customer service, "for" and "in" are two different products.
Copilot in Service includes all the fantastic functionality offered inside of the D365 Customer Service application.
Copilot for Service is the ability to have Copilot functionality used with 'other' service apps such as Zendesk, SFDC, and SNow.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8d5f243-3ef0-d604-561c-4d9a18300a2f
* Version Independent ID: f8d5f243-3ef0-d604-561c-4d9a18300a2f
* Content: [Welcome to Microsoft Copilot for Sales](https://learn.microsoft.com/en-us/microsoft-sales-copilot/introduction)
* Content Source: [articles/introduction.md](https://github.com/MicrosoftDocs/microsoft-salescopilot-docs/blob/main/articles/introduction.md)
* Service: **microsoft-sales-copilot**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**
*

**Comment by sbmjais** [comment]
Hi @gkcoast2coast, the name of the product/SKU is Copilot for Sales. It's similar to what you mentioned for D365 Customer Service.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
