### ISSUE TITLE
Disable Sales Co-Pilot Advertisement/Notification Banner in outlook

### ISSUE THREAD

**Issue by josh-ocp** [MicrosoftDocs/microsoft-salescopilot-docs#2]
Our company would like an option to disable the Sales Co-Pilot Banner Advertisement that appears on individual emails without needing to disable the tool itself company wide. We would also like a way to scope the tool for only certain groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 103164c7-39c3-57da-5027-4c4156d33a55
* Version Independent ID: 103164c7-39c3-57da-5027-4c4156d33a55
* Content: [Configure Sales Copilot for Microsoft 365 apps](https://learn.microsoft.com/en-us/microsoft-sales-copilot/m365-admin-setting)
* Content Source: [articles/m365-admin-setting.md](https://github.com/MicrosoftDocs/microsoft-salescopilot-docs/blob/main/articles/m365-admin-setting.md)
* Service: **microsoft-sales-copilot**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Hi @josh-ocp, the steps to turn off email notification are mentioned at: https://learn.microsoft.com/en-us/microsoft-sales-copilot/m365-admin-setting. Please let us know if this resolves your issue.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
