### ISSUE TITLE
Supported languages - roadmap link would help

### ISSUE THREAD

**Issue by fonsell** [MicrosoftDocs/microsoft-salescopilot-docs#25]
Any timeline or more information about when will other languages be supported in drafting an email in Copilot for Sales? Long waited information since M365 Copilot already supports other languages like Finnish.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34393f54-44cf-6210-b220-8dc363f7611a
* Version Independent ID: 34393f54-44cf-6210-b220-8dc363f7611a
* Content: [Draft an email message within Copilot for Sales app](https://learn.microsoft.com/en-US/microsoft-sales-copilot/use-copilot-kickstart-email-messages#bkmk-lang)
* Content Source: [articles/use-copilot-kickstart-email-messages.md](https://github.com/MicrosoftDocs/microsoft-salescopilot-docs/blob/main/articles/use-copilot-kickstart-email-messages.md)
* Service: **microsoft-sales-copilot**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
@fonsell - Thanks for the comment. We recently updated the document by adding a table with the feature-language pair: https://learn.microsoft.com/en-US/microsoft-sales-copilot/supported-languages#ai-in-copilot-for-sales

We are working towards adding more languages but can't commit to a date. We'll update the document as soon as new languages are supported.

Closing this issue.

**Comment by fonsell** [comment]
And the table is again outdated since at least Japan language now seems to be available on the list
