### ISSUE TITLE
Licensing Info

### ISSUE THREAD

**Issue by CarrieDavisD365** [MicrosoftDocs/microsoft-salescopilot-docs#27]
It would be helpful to state which license per feature described is required i.e. Just D365 Sales Enterprise/Premium or whether the Copilot for Sales license is also required. Just showing this image stating which level it sits in would save users time.

![image](https://github.com/MicrosoftDocs/microsoft-salescopilot-docs/assets/63355944/b5cfdf70-3e9f-4172-a5b7-2040ba24fd7a)

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6bd9a2d-5da1-67c4-d8a7-e7f323d292fe
* Version Independent ID: a6bd9a2d-5da1-67c4-d8a7-e7f323d292fe
* Content: [Create a contact in your CRM from Copilot for Sales](https://learn.microsoft.com/en-us/microsoft-sales-copilot/create-contact-crm-sales-copilot)
* Content Source: [articles/create-contact-crm-sales-copilot.md](https://github.com/MicrosoftDocs/microsoft-salescopilot-docs/blob/main/articles/create-contact-crm-sales-copilot.md)
* Service: **microsoft-sales-copilot**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for the feedback. As mentioned in the in the FAQ here https://learn.microsoft.com/en-us/microsoft-sales-copilot/sales-copilot-faq#will-copilot-for-sales-be-included-in-dynamics-365-sales-subscriptions and the next question, standard capabilities are included with D365 Sales Enterprise/Premium licenses. We have plans to add license requirements to each feature document in the coming month. 
Closing this issue.
