### ISSUE TITLE
AI languages list is imcomplete

### ISSUE THREAD

**Issue by fonsell** [MicrosoftDocs/microsoft-salescopilot-docs#28]
There is already 7 languages supported in AI in Copilot for Sales instead of this list there's also Italian, Danish and Dutch already available

AI in Copilot for Sales
AI in Copilot for Sales for suggested email content and email summary is available in the following languages:

English
French
German
Spanish

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a22e9fd8-8267-a014-ba96-5165512d7fd8
* Version Independent ID: a22e9fd8-8267-a014-ba96-5165512d7fd8
* Content: [Supported languages in Copilot for Sales for Outlook and Teams](https://learn.microsoft.com/en-us/microsoft-sales-copilot/supported-languages)
* Content Source: [articles/supported-languages.md](https://github.com/MicrosoftDocs/microsoft-salescopilot-docs/blob/main/articles/supported-languages.md)
* Service: **microsoft-sales-copilot**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for the feedback. The language list is now updated. Closing this issue.
