### ISSUE TITLE
Viva Topics deprecated

### ISSUE THREAD

**Issue by VivianVoss** [MicrosoftDocs/microsoft-salescopilot-docs#31]
In the integrate with other applications documentations, Viva Topics is very prominent on the list. Viva Topics has now been deprecated as a product and will be retired February, 22 2025. There should be a note or a warning added to the documentation here.

**Comment by sbmjais** [comment]
Thank you for the comment. We have added notes about deprecation in the topic and published them live. Closing this issue.

- https://learn.microsoft.com/en-us/microsoft-sales-copilot/use-extensions#integrate-with-viva-topics
- https://learn.microsoft.com/en-us/microsoft-sales-copilot/view-understand-meeting-summary#view-viva-topics-in-meeting-summary-preview
- https://learn.microsoft.com/en-us/microsoft-sales-copilot/deprecations-copilot-for-sales
